Import('env')
import SatSCons

x

###########################################################################

sources = SatSCons.GlobSources()
SatSCons.StandardTargets(env)
SatSCons.Lib(env, 'Packets',  sources)
SatSCons.Doxygen(env,sources)
